# Generated by Django 6.0.3 on 2026-03-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(help_text='Например: Центральный район, Красноярск', max_length=200, verbose_name='Локация')),
                ('duration', models.CharField(blank=True, help_text='Например: 2 дня / 1 ночь', max_length=100, verbose_name='Продолжительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurants', models.ManyToManyField(related_name='tours', to='main.restaurant', verbose_name='Включённые рестораны')),
            ],
            options={
                'verbose_name': 'Гастротур',
                'verbose_name_plural': 'Гастротуры',
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reviews', to='main.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв на тур',
                'verbose_name_plural': 'Отзывы на туры',
            },
        ),
    ]
