# Generated by Django 6.0.3 on 2026-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
